### ISSUE TITLE
Bug: Cannot delete a run profile

### ISSUE THREAD

**Issue by JayVDZ** [TetronIO/JIM#82]
Cannot delete a run profile as it's still referenced by an Activity.

```
[15:51:47 WRN] Unhandled exception rendering component: An error occurred while saving the entity changes. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 23503: update or delete on table "ConnectedSystemRunProfiles" violates foreign key constraint "FK_Activities_ConnectedSystemRunProfiles_ConnectedSystemRunPro~" on table "Activities"

DETAIL: Key (Id)=(2) is still referenced from table "Activities".
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|223_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: 23503
    MessageText: update or delete on table "ConnectedSystemRunProfiles" violates foreign key constraint "FK_Activities_ConnectedSystemRunProfiles_ConnectedSystemRunPro~" on table "Activities"
    Detail: Key (Id)=(2) is still referenced from table "Activities".
    SchemaName: public
    TableName: Activities
    ConstraintName: FK_Activities_ConnectedSystemRunProfiles_ConnectedSystemRunPro~
    File: ri_triggers.c
    Line: 2609
    Routine: ri_ReportViolation
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at JIM.PostgresData.Repositories.ActivityRepository.CreateActivityAsync(Activity activity) in C:\Users\JayVanderZant\OneDrive\Source\JIM\JIM.PostgresData\Repositories\ActivitiesRepository.cs:line 23
   at JIM.Application.Servers.ActivityServer.CreateActivityAsync(Activity activity, MetaverseObject initiatedBy) in C:\Users\JayVanderZant\OneDrive\Source\JIM\JIM.Application\Servers\ActivityServer.cs:line 35
   at JIM.Application.Servers.ConnectedSystemServer.DeleteConnectedSystemRunProfileAsync(ConnectedSystemRunProfile connectedSystemRunProfile, MetaverseObject initiatedBy) in C:\Users\JayVanderZant\OneDrive\Source\JIM\JIM.Application\Servers\ConnectedSystemServer.cs:line 736
   at JIM.Web.Pages.Admin.ConnectedSystemDetail.HandleRunProfileDeleteAsync(ConnectedSystemRunProfile connectedSystemRunProfile) in C:\Users\JayVanderZant\OneDrive\Source\JIM\JIM.Web\Pages\Admin\ConnectedSystemDetail.razor:line 996
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudMenuItem.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudListItem.OnClickHandlerAsync(MouseEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by JayVDZ** [comment]
Fixed in commit e013266. 

When deleting entities referenced by Activities (Run Profiles, Sync Rules, MVOs, Data Generation Templates), the Activity FK is now nulled out before deletion. The Activity's `TargetName` property preserves the entity name for audit history.
